# Generated by Django 4.1.2 on 2022-10-30 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_middleware', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newstats',
            options={'verbose_name': 'NewStat', 'verbose_name_plural': 'NewStats'},
        ),
    ]
